name: sharqi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.2.3
  webview_flutter: ^4.4.4
  provider: ^6.1.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  image_path: "assets/icons/launcher icon.png"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
